### PR TITLE
Add settings framework and new settings

### PR DESCRIPTION
**Pull request by somini**
Added a way to run extra commands after each jump.

Using this framework, add a way to open the current fold and to center
the screen.

### CODE REVIEW

**Comment by thinca** [comment]
Good.
I think `g:visualstar_extra_commands` is more simple and flexible.

```vim
let g:visualstar_extra_commands = 'zzzv'
```

How do you think?

**Comment by somini** [comment]
Could be.
My solution is more "batteries included", but that could allow for more flexibility.

I'll set it up so that `g:visualstar_extra_commands` overrides any other settings, but I keep the other options too.

**Comment by thinca** [comment]
Thanks :smiley: 
I don't want to increase options.
A lot of options make the behavior complicated.
Only `g:visualstar_extra_commands` is enough.

**Comment by somini** [comment]
Very well.
I've changed it and squashed it to a single commit.

My example of using it for opening folds and centring on the screen is on the helpfile. :D

**Comment by thinca** [comment]
Very good.  Thanks!

**Pull request merged**
